import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;

/**
 * Class to analyse logs generated by the simulator
 * @author alastair
 */
public class Analyser {

	// An ArrayList of the various logs
	private ArrayList<ArrayList<String>> logs;
	
	public Analyser() {
		logs = new ArrayList<ArrayList<String>>();
	}
	
	/**
	 * Loads all the logs from the log file
	 * @author alastair
	 */
	public void loadLogs() {
		try {
			File log = new File("Logs.dat");
			Scanner scan = new Scanner(log);
		   	   try {
		   		ArrayList<String> records = null;
		   		while(scan.hasNext())
		   		{
		   			String line = scan.next();
					if(line.equalsIgnoreCase("[start]"))
		   			{
						records = new ArrayList<String>();
		   			}
		   			else if (line.equalsIgnoreCase("[finish]"))
		   			{
		   				logs.add(records);
		   			}
		   			else
		   			{
		   				records.add(line);
		   			}
		   		}
		   	   }
		   	   catch(NullPointerException e){
		   		   System.out.println("Error writing logs \n"+e);
		   	   }
		}
		catch(IOException e) {
		    System.out.println("Error writing logs \n"+e);
		}
	}

	/**
	 * Checks the logs to determine which animals lastest the longest
	 * @author alastair
	 */
	public void checkSuccessor() {
		// Find the most common successor
		String ultimate = null;
		for(int i=0;i<logs.size();i++)
		{
			ArrayList<String> records = logs.get(i);
			ultimate = records.get(records.size());
			System.out.println(ultimate);
		}
	}
	
	/**
	 * Checks to see how many logs there are records
	 * @author alastair
	 * @return Number of logs
	 */
	public int getLogCount() {
		return logs.size();
	}
	
	/**
	 * Checks to see how many logs are worthy of analysis 
	 * @author alastair
	 * @return Number of logs with over 100 steps
	 */
	public int getWorthyLogCount() {
		int count = 0;
		for(int i=0;i<logs.size();i++)
		{
			ArrayList<String> records = logs.get(i);
			if(records.size() > 100){count++;}
		}
		return count;
	}
}
